_target_: src.losses.CompositeLoss
_convert_: all

losses:
  cwd:
    _target_: src.losses.ChannelWiseKD
    temperature: 1.0
    ce_weight: 1.0
    cwd_weight: 3.0

  seg:
    _target_: src.losses.DiceLoss
    ce_weight: 1.0
    dice_weight: 1.0
    smooth: 1.0
    ignore_index: ${data.dataset.ignore_index}

weights:
  cwd: 0.7
  seg: 0.3
