defaults:
  - _self_
  - data: cifar10
  - model/teacher: resnet56_cifar
  - model/student: resnet20_cifar
  - loss: hinton_kd
  - optimizer: adam
  - scheduler: cosine
  - trainer: default
  - experiment: null

name: default

# Воспроизводимость
seed: 42
deterministic: true
# если нет детерменированной реализации при false ловим ошибку, при true запускаемся
deterministic_warn_only: false # лучше держать false

device: auto  # auto | cuda | cuda:N | cpu

ckpt_path: null

# Трекинг в ClearML
# Выключен по умолчанию, чтобы тесты работали оффлайн
clearml:
  enabled: false
  project: Juicer-for-models
  tags: []  # эксперименты добавляют свои

# Логи Hydra
hydra:
  run:
    dir: outputs/${name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/${name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: false # входные пути всегда от корня репо, выходные по явно запрошенному output_dir
